name: rxnrecer-minimal
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scikit-learn>=1.0.0
  - biopython>=1.80
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - tqdm>=4.60.0
  - requests>=2.25.0
  - pyyaml>=6.0
  - h5py>=3.7.0
  - feather-format>=0.4.1
  - pip
  - pip:
    - transformers>=4.20.0
    - accelerate>=0.20.0
    - sentencepiece>=0.1.97
    - protobuf>=3.20.0
    - openai>=0.28.0
    - anthropic>=0.3.0
    - tiktoken>=0.4.0
    - tenacity>=8.0.0
    - python-dotenv>=0.19.0
    - click>=8.0.0
    - rich>=12.0.0
    - typer>=0.6.0
